### ISSUE TITLE
Column headers don't scroll in library

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/floorspace.js#8]
When a FloorspaceJS geometry is created and space options are expanded, captions do not scroll while the contents are scrolling creating confusion. Please see video below:
[bug report video.webm](https://github.com/openstudiocoalition/OpenStudioApplication/assets/4415312/428cec46-7c37-430b-bac8-4dd37e0e408a)

Reported by @manuvarkey

**Comment by manuvarkey** [comment]
Pull request #11 raised to fix issue.
