### ISSUE TITLE
The input field for setting North Axis in FloorspaceJS geometry is overflowing.

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/floorspace.js#9]
The input field for setting North Axis in FloorspaceJS geometry is overflowing.

![image](https://github.com/openstudiocoalition/floorspace.js/assets/1327850/38436f67-e5c4-409e-9c34-55c7965fd502)

Reported by @manuvarkey

**Comment by manuvarkey** [comment]
Pull request #11 raised to fix issue.
